{% set name = "ipyautoui" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ipyautoui-{{ version }}.tar.gz
  sha256: 2b44a4693c6949744a7d2b8027a7f3ad01fedc2887a07eac6c667e885c3e67fa

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python >={{ python_min }}
    - immutables
    - ipython
    - ipywidgets >8
    - ipydatagrid <=1.3.2
    - ipyfilechooser
    - ipyvuetify
    - markdown
    - jsonref
    - numpy
    - openpyxl
    - requests
    - pandas
    - pydantic >=2
    - pydantic-settings
    - pydantic-extra-types
    - pyyaml
    - stringcase
    - wcmatch
    - deepdiff
    - datamodel-code-generator >=0.28.5
    - xlsxdatagrid >=0.3.2,<0.4

test:
  imports:
    - ipyautoui
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  summary: wrapper that sits on top of ipywidgets and other ipy widget libraries to template / automate the creation of widget forms. Uses pydantic to create defined data-container and serialisation to JSON. Includes example patterns for adding new custom widgets.
  license: BSD-3-Clause
  license_file: BSD-3-Clause.txt
  home: https://github.com/maxfordham/ipyautoui
  doc_url: https://maxfordham.github.io/ipyautoui
  dev_url: https://github.com/maxfordham/ipyautoui

extra:
  recipe-maintainers:
    - jgunstone
    - mwcraig
